version: 2
updates:
  # npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    groups:
      # SvelteKit and related packages
      sveltekit:
        patterns:
          - '@sveltejs/*'
          - 'svelte'
          - 'svelte-*'
      # Storybook and related packages
      storybook:
        patterns:
          - '@storybook/*'
          - 'storybook'
      # Vite and related packages
      vite:
        patterns:
          - 'vite'
          - '@vitejs/*'
          - 'vitest'
      # Cloudflare-related packages
      cloudflare:
        patterns:
          - '@cloudflare/*'
          - 'wrangler'
      # Type definition packages
      types:
        patterns:
          - '@types/*'
      # Linting tools
      linters:
        patterns:
          - 'eslint*'
          - 'prettier*'
          - '@eslint/*'
          - '@typescript-eslint/*'
      # Testing tools
      testing:
        patterns:
          - 'playwright'
          - '@playwright/*'
          - 'vitest'
          - '@vitest/*'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'ci'
      include: 'scope'
